### PR TITLE
Get vm id from wslhost.exe command line

### LINKED ISSUE #42: wslbridge2 won't load on mintty/wsltty (ERROR: GetVmId:312: CreateLxProcess: A null reference pointer was passed to the stub.)
Reposting bug report from: https://github.com/mintty/wsltty/issues/356

After being driven crazy by persistent bugs in several different terminal apps (including the two official Microsoft ones), I had hoped that mintty would be a simple and bug free experience -- and it has been for the past few months.  But today for no apparent reason, it stopped loading.  I booted my Windows 10 yesterday and launched my WSL Ubuntu and loaded my local web server.  When I woke up today, I noticed my local web server wasn't running.  Tried loading Ubuntu from my usual desktop shortcut, but it closed instantly.

I tried opening a `CMD.EXE` terminal, then ran `bash`, which launched my Ubuntu without issues.

I exited out of Ubuntu and in the same `CMD.EXE` terminal, went to my custom portable wsltty install folder and ran this command:

`bin\mintty.exe -w Max --hold=Always --Title="Ubuntu Terminal" --configdir=. --icon=Ubuntu.ico --WSL= -`

That gave me the following error:

`/bin/wslbridge2: Exit 1.`

mintty_oBnjVti8Tl

I then tried loading up `mintty.exe` terminal with `bash` as the command.

`bin\mintty.exe -w Max --hold=always --Title="Ubuntu Terminal" --configdir=. --icon=Ubuntu.ico bash`

Which gave me the following error:

`stty: 'standard input': Inappropriate ioctl for device`

When I run this:

`bin\mintty.exe --version`

It outputs:

`mintty 3.7.1 (x86_64-pc-cygwin) -- wsltty 3.7.1`

When I run `wslbridge2.exe --help` it gives me:

```
wslbridge2 v0.12 : Runs a program within a Windows Subsystem for Linux (WSL) pty.
Copyright (C) 2019-2022 Biswapriyo Nath.
```

And when I directly run `wslbridge2.exe` it outputs:

`ERROR: GetVmId:312: CreateLxProcess: A null reference pointer was passed to the stub.`

The wslbridge2 error I get mentions VM ID, and looking at the main wslbridge2 github page I see this under the "CAVEATS" section:

> There is no documented way to get VM ID of running WSL2 utility VM. See this https://github.com/microsoft/WSL/issues/4131. Hence GetVmId.cpp will change in future Windows 10 releases due to usage of undocumented COM methods.

Maybe those "undocumented COM methods" were updated by Windows, and now it can't get the ID?

@exeral stated that switching to WSL1 as a workaround does avoid the wslbridge2 issue:
> with `wsl --set-version Ubuntu 1` I was able to get it working again. but that's not a good solution for me

I went and searched Microsoft.com for a list of recent Windows Updates for Windows 10, and found this update (KB5043131) from September 24th, 2024:

https://support.microsoft.com/en-us/topic/september-24-2024-kb5043131-os-build-19045-4957-preview-2d4a5c54-ac58-4bdb-8685-57d578650e5f

However, when I then looked for my list of installed Windows Updates, I discovered that update isn't actually installed.  My most recent Windows Update showing up is from September 18th, 2024:

ApplicationFrameHost_P0j6YaqK4v

But WSL2 was working fine in wsltty after that update a week ago.  I don't see any Windows Updates during the past few days... so I'm not sure how this broke all of a sudden?  Does WSL2 get auto-updated outside of Windows Update somehow?  Maybe from the Microsoft Store?

-------------

These are other users who area also experiencing the same issue:

@exeral, @rluetzner, @xuefer, @ypnos

Comparing our `wsl --version` outputs, we're all using the same versions of these apps:

```
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
```

And for Windows 10 versions, we all have one of these 3 versions:

```
Windows Version: 10.0.22631.4169
Windows Version: 10.0.19045.4894
Windows Version: 10.0.19042.2965
```

Any clues, @benhillis, @Biswa96, or anyone else?

### PR DESCRIPTION
**Pull request by MrVinkel**
Lookup VM ID for WSL 2 instances by looking at the command line arguments for wslhost.exe

fixes #42 

Tested on WSL version:
WSL version: 2.3.24.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.65
MSRDC version: 1.2.5620
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.22631.4169

### CODE REVIEW

File: src/wslbridge2.cpp [hunk 1]
```diff
@@ -384,12 +385,12 @@ int main(int argc, char *argv[])
     {
         // wsltty#302: Start dummy process after ComInit, otherwise RPC_E_TOO_LATE.
         // wslbridge2#38: Do this only for WSL2 as WSL1 does not need the VM context.
+        // wslbridge2#42: Required for WSL2 to get the VM ID.
         if (LiftedWSLVersion)
             start_dummy(wslPath, wslCmdLine, distroName, debugMode);
 
-        const HRESULT hRes = GetVmId(&DistroId, &VmId, LiftedWSLVersion);
```
Comment (Biswa96) [inline src/wslbridge2.cpp]: Instead of removing the COM logic, would it be possible to add the registry check after COM failed? 

In this condition,

https://github.com/Biswa96/wslbridge2/blob/5b2b652d1a7355b004e7860b4370a585737e5ac9/src/GetVmId.cpp#L312

Comment (MrVinkel) [reply src/wslbridge2.cpp]: done
